// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PP.EntityFramework.Migrations
{
    [DbContext(typeof(PPDbContext))]
    partial class PPDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PP.Domain.Models.Angajati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa");

                    b.Property<string>("Angajat");

                    b.Property<string>("CodAngajat");

                    b.Property<DateTime>("DataAngajarii");

                    b.Property<DateTime>("DataNasterii");

                    b.Property<int>("IdSector");

                    b.Property<string>("Linie");

                    b.Property<int?>("SectorID");

                    b.Property<string>("Sex");

                    b.Property<string>("Telefon");

                    b.Property<bool>("status");

                    b.HasKey("Id");

                    b.HasIndex("SectorID");

                    b.ToTable("Angajati");
                });

            modelBuilder.Entity("PP.Domain.Models.Articole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Articol");

                    b.Property<double?>("Centes");

                    b.Property<double?>("CostProductie");

                    b.Property<string>("Descriere");

                    b.Property<string>("Finete");

                    b.Property<int>("IdSector");

                    b.Property<int?>("IdStagiune");

                    b.Property<string>("Note");

                    b.Property<double?>("Prezzo");

                    b.Property<int?>("SectorID");

                    b.Property<string>("Stagione");

                    b.HasKey("Id");

                    b.HasIndex("SectorID");

                    b.ToTable("Articole");
                });

            modelBuilder.Entity("PP.Domain.Models.ProgrammerTask", b =>
                {
                    b.Property<int>("ProgrammerTaskID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleID");

                    b.Property<DateTime>("EndTask");

                    b.Property<int>("JobTypeID");

                    b.Property<string>("Note");

                    b.Property<int>("ProgrammerID");

                    b.Property<DateTime>("StartTask");

                    b.Property<bool>("TaskCompleted");

                    b.HasKey("ProgrammerTaskID");

                    b.HasIndex("ArticleID");

                    b.ToTable("ProgrammerTask");
                });

            modelBuilder.Entity("PP.Domain.Models.Sector", b =>
                {
                    b.Property<int>("SectorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SectorName");

                    b.HasKey("SectorID");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("PP.Domain.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("JobType");

                    b.Property<DateTime?>("LastLogin");

                    b.Property<bool>("OnlineStatus");

                    b.Property<string>("Password");

                    b.Property<string>("Telephone");

                    b.Property<string>("Username");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PP.Domain.Models.Angajati", b =>
                {
                    b.HasOne("PP.Domain.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorID");
                });

            modelBuilder.Entity("PP.Domain.Models.Articole", b =>
                {
                    b.HasOne("PP.Domain.Models.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorID");
                });

            modelBuilder.Entity("PP.Domain.Models.ProgrammerTask", b =>
                {
                    b.HasOne("PP.Domain.Models.Articole", "Articole")
                        .WithMany()
                        .HasForeignKey("ArticleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
